name: Build and Package Mod

on:
  push:
    branches: [ installer ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022"

    - name: Build Project (Release)
      run: |
        cd build
        cmake --build . --config Release

    - name: Copy Built Files to Installer Directory
      run: |
        copy build\Release\dualsense-mod.dll installer\files\
        copy build\Release\dualsensitive-service.exe installer\files\

    - name: Build Inno Setup Installer
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\ControlDSModInstaller.iss

    - name: Upload Installer EXE
      uses: actions/upload-artifact@v4
      with:
        name: Control-DualSensitive-Mod_Setup
        path: installer/Control-DualSensitive-Mod_Setup.exe

    - name: Prepare Manual Install ZIP
      run: |
        mkdir -p manual-install/plugins/DualSensitive
        cp installer/files/xinput1_4.dll manual-install/
        cp installer/files/dualsense-mod.ini manual-install/plugins/
        cp installer/files/dualsense-mod.dll manual-install/plugins/
        cp installer/files/dualsensitive-service.exe manual-install/plugins/DualSensitive/
        cp installer/files/launch-service.vbs manual-install/plugins/DualSensitive/
        cd manual-install
        zip -r ../Control-DualSensitive-Mod_Manual.zip .

    - name: Upload Manual Install ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Control-DualSensitive-Mod_Manual
        path: Control-DualSensitive-Mod_Manual.zip

